#pragma once
#ifndef SCRABBLE_CONSTANTS_H
#define SCRABBLE_CONSTANTS_H

const int DEFAULT_LETTERS_COUNT = 10;
const int DEFAULT_ROUNDS_COUNT = 5;
const int DEFAULT_ROUNDS_SHUFFLES = 2;
const int DEFAULT_REMAINING_TRIES = 3;
const int LETTERS_COUNT = 26;
const int LOWERCASE_A_ASCII_CODE = 97;
const int LOWERCASE_Z_ASCII_CODE = 122;

const char HEADER_SEPARATOR = '=';
const int HEADER_SEPARATOR_LENGTH = 25;

#endif //SCRABBLE_CONSTANTS_H
